### ISSUE TITLE
Not wrapping the iframe

### ISSUE THREAD

**Issue by crecorn** [diazemiliano/mapScrollPrevent#1]
I can't get it to wrap the iframe. I even tried to add an id to the iframe and change the script to 
[code] var googleMapSelector = $('#gmap');[/code]

**Comment by diazemiliano-zz** [comment]
**_Can you showme the code. Thanks!**_

First you have to define the selector: `var googleMapSelector = "iframe[src*=\"google.com/maps\"]";`
And finally call the function `$(googleMapSelector).mapScroll();`
Or `$("iframe[src*=\"google.com/maps\"]").mapScroll();`

**Comment by diazemiliano-zz** [comment]
@crecorn I've fixed this issue.
The problem was in the css.
