### ISSUE TITLE
No delay when using mouse

### ISSUE THREAD

**Issue by strarsis** [diazemiliano/mapScrollPrevent#10]
A PC user has to hold the mouse primary button over the iframe for the given delay to unlock it.
Wouldn't it be nicer when a mouse user just clicks on it to unlock it without holding the mouse button down?

**Comment by diazemiliano-zz** [comment]
I think that without the delay, the user may cause unwanted unlocks in small touch screen devices.

**Comment by strarsis** [comment]
This makes sense.
But could normal click for users _only with a mouse_ be used?

**Comment by diazemiliano-zz** [comment]
I'm sorry but the best solution for better compatibility, is pretend the same behavior for all devices and input methods. Anyway I'll think how to implement this.
