### ISSUE TITLE
Unlocks all scrollprevented iframes at once

### ISSUE THREAD

**Issue by strarsis** [diazemiliano/mapScrollPrevent#11]
When selecting multiple iframes (which can happen often and should be supported),
unlocking one of the iframes will unlock all of them, too.

Each iframe should be unlockable/lockable individually - or at least an option provided for this.

**Comment by ghost** [comment]
Assign id's to your iframes and change the selector

Example

```
    var googleMapSelector = "#map1";
    var options = { pressDuration: 1000 };
    $(googleMapSelector).scrollprevent(options).start();
```

**Comment by strarsis** [comment]
So this would be the usual behaviour of a JQuery plugin - 
that a list of elements passed to it would behave like a group/single element?

Based on your example, I now use a class selector and each() to apply on individual instances.

**Comment by diazemiliano-zz** [comment]
Bug Fixed check latest changes at https://github.com/diazemiliano/googlemaps-scrollprevent/commit/e227b5864898a1e8bb04ecfc8df802a8bdd12b7d
Thanks!
