### ISSUE TITLE
Width Issues on smaller screens

### ISSUE THREAD

**Issue by jsalwen** [diazemiliano/mapScrollPrevent#13]
On an iPhone, with the plugin active, the embedded Google Map is narrower than expected, and it "jiggles" and gets narrower as I scroll down.

I can also recreate a similar issue in a browser with a narrow width.

To recreate:
- Goto: http://www.srll.net.prod.sportngin.com/davidson1
- Resize window to a narrower width
- Once it gets to a single column, resize narrower and wider (jiggle it)
  -- the google map iframe gets so small it almost disappears
- reload the page, which the narrow (phone size) width
  -- the iframe is not filling the screen

I'm happy to help fix and/or test.
# showcase

**Comment by diazemiliano-zz** [comment]
Hi you must use a responsive approach in your map.
I'm sorry but this isn't a plugin error. Check your theme css and compare with the main example in https://diazemiliano.github.io/googlemaps-scrollprevent/

Thanks and lucky with that!
