### ISSUE TITLE
Wordpress Usage Example Error

### ISSUE THREAD

**Issue by adibbz** [diazemiliano/mapScrollPrevent#14]
Hey, thanks for this! Super handy. 

Just a heads up in the wordpress usage example, the function names are wrong in the add_action hook. They have dashes instead of underscores. Took me longer than I'd like to admit to find this error.😉

**Comment by diazemiliano-zz** [comment]
Sorry for that.
Fixed in https://github.com/diazemiliano/googlemaps-scrollprevent/commit/3b8e5d487a752e4e744103308666bee3eba54cb4 .
