### ISSUE TITLE
Cannot apply on 100% iframe

### ISSUE THREAD

**Issue by gleenk** [diazemiliano/mapScrollPrevent#2]
How to preserve 100% width and responsiveness of the iframe while using your plugin?

**Comment by MicheleV** [comment]
same issue here, any idea?

**Comment by cnc137** [comment]
I solved this problem on a client's "Coming Soon" page (full site coming soon) that you can view at http://st-clarence.org. The Google Maps code is towards the bottom of the page above the brown footer.

I used the Google Maps responsive code that was generated at http://embedresponsively.com, but then modified it a little as you will see below. I tested this in Internet Explorer 9, Internet Explorer 10, Internet Explorer 11, Firefox, Chrome, Opera, and Safari and it worked as expected. I also tested it on my iPhone 5s (iOS), EVGA NVIDIA Tegra Note 7 (Android), and Nokia Lumia 635 (Windows Phone 8.1) and it is working on these devices.

As a side note, I am using the [Zurb Foundation](http://foundation.zurb.com) RWD framework for this website, but I would think the code below should work without it.

**HTML**

```
<div id="map">
  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2992.723902953985!2d-81.95416199999998!3d41.401801999999996!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8830915571451ca5%3A0xcc4e63394a7cd697!2sSt+Clarence+Church!5e0!3m2!1sen!2sus!4v1422906180676" width="100%" height="100%" frameborder="0"></iframe>
</div>
```

**CSS**

```
/* Google Maps, mapScrollPrevent, and Embed Responsively Styling */

#map {
    width: 100%;
    height: 250px;
    position: relative;
    z-index: 10;
    overflow: hidden;
}
#map iframe {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 250px;
    max-height: 250px;
}
.map-overlay p {
    padding-top: 1.5% !important;
    padding-bottom: 1.5% !important;
}
```

**JavaScript**

```
// mapScrollPrevent - Easy solution to the problem of page scrolling with new "Google Maps Iframe Embed".
// Documentation can be found at: https://github.com/diazemiliano/mapScrollPrevent

<script src="js/vendor/mapScrollPrevent.js"></script>

$(function() {
  // Only Google Maps Selector
  var googleMapSelector = "iframe[src*=\"google.com/maps\"]";
  var options = {
          overlayMessage:"Click/Touch to Navigate"
          };
  $(googleMapSelector).mapScrollPrevent(options);
});
```

You may also want to look at my [Pull Request](https://github.com/diazemiliano/mapScrollPrevent/pull/3) to fix mapScrollPrevent in Internet Explorer 11 so the links are able to be clicked on the map after you click to remove the overlay.

I hope this makes sense and helps get your code working responsively with mapScrollPrevent.

**Comment by diazemiliano** [comment]
Hi, I'm currently having some health problems. Please wait a little. I'm sorry.

**Comment by diazemiliano-zz** [comment]
Hi now the `Map overlay` dynamically adjust its dimensions on `Window` or `iframe` resize events. So doesn't matter if the map is responsive or not the overlay always fit in.
