### ISSUE TITLE
Install on Wordpress

### ISSUE THREAD

**Issue by LPBEV** [diazemiliano/mapScrollPrevent#4]
Hi there !
First thanks for your plugin, I'm sure that will help a lot of people like me to do things more easely.

My issue is that I installed it correctly but I don't understand how to apply it to my Google Maps iframe.

How to apply the ScrollPrevent to it ?
Am I have to install Jquery before ? (I think that Wordpress has it natively) Am I have to put the iframe code between <div> ? With which class ?
## Thanks for your answer.

Rémi

**Comment by diazemiliano-zz** [comment]
Sorry this branch is discontinued Because It's really easy to implement in wordpress.
I'll add an howto into the readme.
See latest changes to `readme.md` in https://github.com/diazemiliano/googlemaps-scrollprevent/blob/master/README.md
