### ISSUE TITLE
WordPress repository

### ISSUE THREAD

**Issue by StaggerLeee** [diazemiliano/mapScrollPrevent#5]
Put it in WP plugin repository ?
Nobody knows about this plugin.

**Comment by diazemiliano-zz** [comment]
Thanks!
I've back, so I will take all the suggestions.

**Comment by StaggerLeee** [comment]
And try to make it without latest jQuery version, please. Themes and other plugins load older jQuery and your plugin is messing with backend and frontend.

One of them is Pods plugin backend.

**Comment by diazemiliano-zz** [comment]
Done!
