### ISSUE TITLE
click() handler missing in master ("Disable map Interaction on touchscreen")

### ISSUE THREAD

**Issue by mechanicalduck** [diazemiliano/mapScrollPrevent#6]
The dist _minified_ javascript from rawgit CDN, like used by the examples on your site,
https://cdn.rawgit.com/diazemiliano/mapScrollPrevent/master/dist/mapScrollPrevent.min.js 
 is _not_ the one from the current master (though the url indicates it) 
as the click handler is still in the code.

it is missing in the github repo 
https://github.com/diazemiliano/mapScrollPrevent/blob/master/dist/mapScrollPrevent.js 
(also in the minified version https://github.com/diazemiliano/mapScrollPrevent/blob/master/dist/mapScrollPrevent.min.js).

According to the log, it has been removed in the last commit of these files 
("Disable map Interaction on touchscreen").
Without the click handler, it is impossible to activate the maps by using the mouse (clicking).

Thank you.
With best regards

**Comment by diazemiliano-zz** [comment]
**I'm sorry**. I've forget to push my last local changes!!!
Now https://cdn.rawgit.com/diazemiliano/mapScrollPrevent/master/dist/mapScrollPrevent.min.js it's updated to v0.5.5
Thanks!
