### ISSUE TITLE
pointer-events: auto; when scrolling over

### ISSUE THREAD

**Issue by mechanicalduck** [diazemiliano/mapScrollPrevent#7]
mapScrollPrevents seems to switch pointer-events to auto when the mouse 
is not hovering the iframe and pointer-events to none when the mouse is hovering (scroll-focus).

However, when the user doesn't move the mouse pointer and just scrolls up or down so the mouse pointer scrapes over the iframe, pointer-events will not be set to none 
as with mouse over and the scroll event passes through though.
This can be provoked by scrolling up and down and let the pointer hop a bit.

The main reason why I use this plugin (and why it is so great) is 
that it prevents accidental zooming when scrolling down a page where the iframe is embedded in.

Thank you.
With best regards

**Comment by diazemiliano-zz** [comment]
Thanks, you could showme some working example? I can't reproduce this issue.
**Update:** Could you try if this issue still in the new version? Thanks!
