### ISSUE TITLE
Assume always touch?

### ISSUE THREAD

**Issue by strarsis** [diazemiliano/mapScrollPrevent#9]
In the Pre-Release summary:
"Instead of this the future versions assume touchscreen events as default events."

I also embed touch aware apps in iframes on sites for PC (using mouse pointer).
Responsive site means also that all those devices, from mobile up to large screen PC (using mouse pointer) can use the site, responsive is not limited to screen size or pixel density but also encompasses present input devices.

Does this mean mouse only users won't be blocked from accidentally scrolled anymore in the next releases?

**Comment by diazemiliano-zz** [comment]
This plugin functions in a compatible way with touch screen events. So is both compatible with touch screen and the rest of the devices that uses a mouse.
In previous versions we used events like `mouseenter` or `mouseleave` that obviously crashes in touchscreen devices.
Using only `mousedown, touchstart` and `mouseup, touchend` events requires a change in the way that the plugin works.
So the summary only means that we make it more compatible :smile: .
